ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-users]]
== User

[[resources-users-create]]
=== 회원 가입

operation::users/create[snippets='http-request,http-response']
operation::users/create[snippets='request-fields,response-fields']

---

[[resources-users-me]]
=== 내정보 조회

operation::users/me[snippets='http-request,http-response']
operation::users/me[snippets='request-headers']
operation::users/me[snippets='response-fields']

---

[[resources-stations]]
== Station

[[resources-stations-create]]
=== 지하철역 생성
operation::stations/create[snippets='http-request,http-response']
operation::stations/create[snippets='request-fields,response-fields']

[[resources-stations-read]]
=== 지하철역 목록 조회
operation::stations/read[snippets='http-request,http-response']
operation::stations/read[snippets='response-fields']

[[resources-stations-single-read]]
=== 지하철역 조회
operation::stations/read/{id}[snippets='http-request,http-response']
operation::stations/read/{id}[snippets='response-fields']

[[resources-stations-delete]]
=== 지하철역 삭제
operation::stations/delete/{id}[snippets='http-request,http-response']
