ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 6
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-users]]
== User


[[resources-users-create]]
=== 회원 가입

operation::users-create[snippets='http-request,request-headers']
operation::users-create[snippets='request-fields,http-response']
operation::users-create[snippets='response-headers,response-fields']


[[resources-users-delete]]
=== 회원 탈퇴

operation::users-delete[snippets='http-request,request-headers']
operation::users-delete[snippets='http-response,response-headers']

[[resources-login]]
=== 로그인 요청

operation::login[snippets='http-request,request-headers']
operation::login[snippets='request-fields,http-response']
operation::login[snippets='response-headers,response-fields']


[[resources-users-me]]
=== 회원정보 요청

operation::users-me[snippets='http-request,request-headers']
operation::users-me[snippets='request-fields,http-response']
operation::users-me[snippets='response-headers,response-fields']

[[resource-find-path]]
=== 최소경로 조회 요청
operation::find-path[snippets='http-request,http-response']


