ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-users]]
== User

[[resources-users-create]]
=== 회원 가입

operation::users/create[snippets='http-request,http-response']
operation::users/create[snippets='request-fields,response-fields']

---

[[resources-users-me]]
=== 내정보 조회

operation::users/me[snippets='http-request,http-response']
operation::users/me[snippets='request-headers']
operation::users/me[snippets='response-fields']

---

[[resources-stations]]
== Station

[[resources-stations-create]]
=== 지하철역 생성
operation::stations/create[snippets='http-request,http-response']
operation::stations/create[snippets='request-fields,response-fields']

[[resources-stations-read]]
=== 지하철역 목록 조회
operation::stations/read[snippets='http-request,http-response']
operation::stations/read[snippets='response-fields']

[[resources-stations-single-read]]
=== 지하철역 조회
operation::stations/read/{id}[snippets='http-request,http-response']
operation::stations/read/{id}[snippets='response-fields']

[[resources-stations-delete]]
=== 지하철역 삭제
operation::stations/delete/{id}[snippets='http-request,http-response']

[[resources-lines]]
== Lines

=== 지하철 노선 생성
operation::lines/create[snippets='http-request,http-response']
operation::lines/create[snippets='request-fields,response-fields']

=== 지하철 노선 목록 받기
operation::lines/read[snippets='http-request,http-response']
operation::lines/read[snippets='response-fields']

=== 지하철 단일 노선 받기
operation::lines/{id}/read[snippets='http-request,http-response']
operation::lines/{id}/read[snippets='path-parameters,response-fields']

=== 지하철 단일 노선 삭제
operation::lines/{id}/delete[snippets='http-request,http-response']
operation::lines/{id}/delete[snippets='path-parameters']

=== 지하철 구간 등록
operation::lines/{id}/edges/create[snippets='http-request,http-response']
operation::lines/{id}/edges/create[snippets='path-parameters,request-fields']

=== 지하철 구간에서 지하철역 삭제
operation::lines/{id}/edges/delete[snippets='http-request,http-response']
operation::lines/{id}/edges/delete[snippets='path-parameters,request-parameters']

[[resources-path]]
== Paths

=== 지하철 경로 받기
operation::paths/read[snippets='http-request,http-response']
operation::paths/read[snippets='request-parameters,response-fields']
