= Subway Application API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[path]]
== 지하철 경로

=== 경로 조회

operation::path[snippets='http-request,http-response']

|===
| 파라미터 | 이름 | 설명
|source|출발역| 출발역의 식별자
|target|도착역| 도착역의 식별자
| stations | 역 목록 | 시작역부터 도착역까지 경유하는 역들의 정보
| stations.id | 식별자 | 역의 식별자
| stations.name | 식별자 | 역 이름
| distance | 거리 | 경유하는 거리
| duration | 소요 시간 | 소요되는 최소 소요 시간
|===


== 지하철 역

=== 역 생성

operation::station/create[snippets='http-request,http-response']

=== 역 조회

operation::station/findStations[snippets='http-request,http-response']

=== 역 삭제

operation::station/deleteStation[snippets='http-request,http-response']

== 지하철 노선

=== 노선 생성

operation::line/create[snippets='http-request,http-response']

=== 노선 조회

operation::line/getLine[snippets='http-request,http-response']

=== 노선 목록 조회

operation::line/showLines[snippets='http-request,http-response']

== 지하철 구간

=== 구간 생성

operation::line/addSection[snippets='http-request,http-response']

=== 구간 조회

operation::line/deleteSection[snippets='http-request,http-response']
